name: pr
on:
  pull_request:
    branches:
      - main

jobs:
  experiment:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
          
      - uses: the-guild-org/shared-config/release-trackback@trackback
        if: ${{ always() }}}
        with:
          token: ${{ secrets.GUILD_BOT_TOKEN }}
          relevantPackages: |
            @theguild/*

