name: pr
on:
  pull_request:
    branches:
      - main

jobs:
  experiment:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - uses: the-guild-org/shared-config/release-trackback@trackback
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

